name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 2 * * 1'
    # scheduled for 02:00 every Monday
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master               # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: sullo/nikto     # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master            # set the branch to merge to
